name: Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: krunkit - latest
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - aarch64-apple-darwin
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew tap slp/krunkit && brew install krunkit
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --release --verbose
      - run: cargo test --release --verbose
